# Generated by Django 2.2.17 on 2020-12-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='gmail',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
