# Generated by Django 2.2.17 on 2021-01-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201230_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundIntro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=750)),
                ('background_image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='filmproduction',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='nextservice',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='ourclients',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='radioadverts',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='client_image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
