# Generated by Django 2.2.17 on 2021-01-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210104_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='comment',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
