# Generated by Django 2.2.17 on 2021-01-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210105_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
